# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{browser_check}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steve Sloan"]
  s.date = %q{2010-09-15}
  s.description = %q{Checks that the users' browser supports certain features, and displays an error message if it doesn't.}
  s.email = %q{steve@conceivian.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "MIT-LICENSE",
     "README.rdoc",
     "app/views/browser_check/_browser_check.html.haml",
     "lib/browser_check.rb",
     "lib/browser_check/browser_info.rb",
     "lib/browser_check/engine.rb"
  ]
  s.homepage = %q{http://github.com/Conceivian/browser_check}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Checks for browser compatability}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<haml>, ["~> 3.0.18"])
      s.add_runtime_dependency(%q<railties>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<actionpack>, ["~> 3.0.0"])
    else
      s.add_dependency(%q<haml>, ["~> 3.0.18"])
      s.add_dependency(%q<railties>, ["~> 3.0.0"])
      s.add_dependency(%q<actionpack>, ["~> 3.0.0"])
    end
  else
    s.add_dependency(%q<haml>, ["~> 3.0.18"])
    s.add_dependency(%q<railties>, ["~> 3.0.0"])
    s.add_dependency(%q<actionpack>, ["~> 3.0.0"])
  end
end

